---
apiVersion: v1
kind: Service
metadata:
  name: csi-azuredisk-controller
  namespace: kube-system
  labels:
    app: csi-azuredisk-controller
spec:
  selector:
    app: csi-azuredisk-controller
  ports:
    - name: metrics
      port: 29604
      targetPort: 29604
  type: ClusterIP
